---
# Entrypoint for Zuul
- project:
    check:
      jobs:
        - pre-commit
        - hardly-tests
    gate:
      jobs:
        - pre-commit

- job:
    name: hardly-tests
    parent: base
    description: Hardly run tests
    run: files/zuul-tests.yaml
