# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

# Tasks common to all images

- name: make packit home dir
  file:
    state: directory
    path: "{{ home_path }}"
    mode: 0776
