# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Hardly prepare
  hosts: all
  tasks:
    - name: Rename run_worker.sh
      command: mv /usr/bin/run_worker.sh /usr/bin/run_worker_.sh
    - name: Install our run_worker.sh
      copy:
        src: run_worker.sh
        dest: /usr/bin/
        mode: 0777
