---
- name: This is a recipe for a container image where hardly-worker tests will run
  hosts: all
  tasks:
    - name: Install test RPM dependencies
      dnf:
        name:
          - python3-flexmock
          - tar
          - rsync
        state: present
    - name: Install pip deps
      pip:
        name:
          - requre
          - pytest
          - pytest-cov
          - pytest-flask
        executable: pip3
