# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
kind: Pod
apiVersion: v1
metadata:
  name: mount-src
spec:
  volumes:
    - name: test-src-pv
      persistentVolumeClaim:
        claimName: test-src-pvc
  restartPolicy: Never
  containers:
    - name: packit-tests
      image: hardly-tests
      volumeMounts:
        - mountPath: /src
          name: test-src-pv
      command: ["bash", "-c", "sleep 10000"]
