---
kind: Template
apiVersion: v1
metadata:
  name: hardly-worker-tests-template
objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: packit-tests
    spec:
      template:
        spec:
          volumes:
            - name: packit-secrets
              secret:
                secretName: packit-secrets
            - name: packit-config
              secret:
                secretName: packit-config
            - name: test-src-pv
              persistentVolumeClaim:
                claimName: test-src-pvc
            - name: test-data-pv
              persistentVolumeClaim:
                claimName: test-data-pvc
          restartPolicy: Never
          containers:
            - name: packit-tests
              image: quay.io/packit/hardly-worker-tests:stg
              # If tag is latest, defaults to Always.
              # imagePullPolicy: Never # IfNotPresent
              workingDir: /src
              env:
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: postgres-secret
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: postgres-secret
                - name: POSTGRESQL_HOST
                  valueFrom:
                    secretKeyRef:
                      key: database-host
                      name: postgres-secret
                - name: POSTGRESQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: postgres-secret
              volumeMounts:
                - name: packit-secrets
                  mountPath: /secrets
                - name: packit-config
                  mountPath: /home/packit/.config
                - name: test-src-pv
                  mountPath: /src
                - name: test-data-pv
                  mountPath: /tmp/test_data
              command: ["bash", "/src/files/run_tests.sh"]
      backoffLimit: 1
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: test-data-pvc
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 1Gi
