# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
# This playbook is running tests inside Zuul
- name: Hardly run tests
  hosts: all
  tasks:
    - name: Install podman
      ansible.builtin.dnf:
        name:
          - podman
        state: present
      become: true
    # Fix the SELinux context for podman
    - name: Create ~/.local/share/
      ansible.builtin.file:
        path: ~/.local/share/
        state: directory
        recurse: true
        setype: data_home_t
    - name: Build test image
      ansible.builtin.command: "make test-image"
      args:
        chdir: "{{ zuul.project.src_dir }}"
    - name: Run tests within a container
      ansible.builtin.command: "make check-in-container"
      args:
        chdir: "{{ zuul.project.src_dir }}"
      environment:
        COLOR: "no"
        SOURCE_BRANCH: "{{ zuul.branch }}"
