# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
# This playbook is running tests inside Zuul
- name: Hardly run tests
  hosts: all
  tasks:
    - name: Install podman
      dnf:
        name:
          - podman
        state: present
      become: true
    - name: Build test image
      command: "make test-image"
      args:
        chdir: "{{ zuul.project.src_dir }}"
    - name: Run tests within a container
      command: "make check-in-container"
      args:
        chdir: "{{ zuul.project.src_dir }}"
      environment:
        COLOR: "no"
        SOURCE_BRANCH: "{{ zuul.branch }}"
